name: Rust

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - uses: cargo-bins/cargo-binstall@75b4bfae1b2c753a6806bbce6e6cb89b602de33c
    - name: Install gnostr
      run: cargo binstall --no-confirm gnostr
    - name: Verify gnostr install
      run: gnostr --help
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
